images: node:18

stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install


test:
  stage: test
  script:
    - npm run test:ci

build:
  stage: build
  script:
    - npm run build